### ISSUE TITLE
Does aioice support ice-lite?

### ISSUE THREAD

**Issue by duhoobo** [aiortc/aioice#15]
RFC 5245 is supported according to README, I thought ICE lite implementation was supported as well. 

I write a demo running behind a NAT, trying to make a connection with WebRTC gateway which employs ICE lite implemetation. 

The demo won't take a role as "controlling agent" while gateway as initiator (OFFERing sdp). This behavior seems not compatible with RFC 5245.

RFC 5245, 2.7.  Lite Implementations

> When a lite implementation
   connects with a full implementation, the full agent takes the role of
   the controlling agent, and the lite agent takes on the controlled
   role.

**Comment by jlaine** [comment]
You are correct there isn't currently any specific code for ICE Lite, I need to read up on the subject.

For your specific use case, to be clear: the gateway (ice lite) is offering the SDP to aioice?

**Comment by ibc** [comment]
Some news here. My scenario is as follows:

* ICE-Lite server (mediasoup).
* Create a PC in `aiortc` that becomes the SDP offerer. In this case everything works without any change.
  * `aiortc` becomes ICE controlling and, hence, DTLS server.
  * mediasoup (the server) becomes ICE controlled (of course, it's ICE Lite) and DTLS client.
* Create a PC in `aiortc` that becomes the SDP answerer. In this case some tricks must be done for it to work:
  * `aiortc` does not understand ICE Lite so it insists in sending Binding requests with `ICE_CONTROLLING` flag.
  * The server rejects it with 487 "Role Conflict" (this is a recent addition).
  * Good news! `aiortc` changes its ICE role and becomes ICE controlling.
  * And ICE connects!
  * Then it's time for DTLS. After inspection, since `aiortc` started as ICE controlled it assumed that it should be DTLS server, and it remains being DTLS server after switching to ICE controlling.
  * Taking that into account I have ICE + DTLS working.

**Comment by jlaine** [comment]
OK, if I understand correctly there is no issue with `aioice` after all: it's an ICE full agent, and behaving correctly right? If so let's move the conversation back to `aiortc`.

**Comment by ibc** [comment]
Let's say it works because we figured out the DTLS role that aiortc assumes regardless it's SDP offerer or SDP answered :)

**Comment by jlaine** [comment]
OK I think this issue can be closed: aioice should now interop correctly with an ICE Lite peer. The only issue I found was that we always used agressive nomination. If you set `connection.remote_is_lite`, aioice will now use regular nomination.
